---
title: "AVENIR Trial"
subtitle: "Primary outcome analysis, all cause mortality"
author: "Ben Arnold F.I. Proctor Foundation (ben.arnold@ucsf.edu)"
date: "latest run: `r Sys.time()`"
output: 
  html_document:
    theme: default
    highlight: pygments
    code_folding: hide
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: true
      smooth_scroll: true
---



# Summary

Make a composite figure from mortality rate and incidence rate ratio (IRR) estimates in the primary and secondary analyses

# Load configuration file
```{r preamble, message=FALSE}
library(here)
here()
source(here("R","0-AVENIR-primary-Config.R"))
```


# Load stored estimates


```{r load stored estimates}
#-------------------------------
# mortality rate estimates and
# incidence rate ratios from
# the primary analysis
#-------------------------------
d_mrates_tx <- read_rds(file=here("output","avenir-mortality-primary-rates-by-tx.rds"))
dIRRs <- read_rds(file=here("output","avenir-mortality-primary-IRRs.rds"))

#-------------------------------
# mortality rate estimates and
# incidence rate ratios from
# the secondary analysis
#-------------------------------
dIRRs_secondary <- read_rds(file=here("output","avenir-mortality-secondary-IRRs.rds"))

#-------------------------------
# create some tx labels for
# plotting
#-------------------------------
d_mrates_tx2 <- d_mrates_tx %>%
    mutate(txlab = factor(tx,levels=c("Azithro 1-59m","Azithro 1-11m","Placebo"),labels=c("Child\nAzithro\n1-59m","Infant\nAzithro\n1-11m","Placebo")))

#-------------------------------
# combine all of the IRRs into
# a single data frame for plotting
# make some variables to potentially
# use in the plots
#
# including 2 permutation p-values
# from 6-AVENIR-mortality-primary-analysis.Rmd/.html
# that were part of formal statistical
# significance testing
#-------------------------------
d_irr <- dIRRs %>%
    bind_rows(dIRRs_secondary) %>%
    mutate(hyp = paste0("Hypothesis ",1:5),
           pval = c("p = 0.0004","p = 0.353","","","")) %>% 
    mutate(irrlab = case_when(
        comparison == "1-59m v Placebo" ~ "Child Azithro\n1-59m\nvs\nPlacebo\n\nP = 0.0004",
        comparison == "1-11m v Placebo" ~ "Infant Azithro\n1-11m\nvs\nPlacebo\n\nP = 0.35",
        comparison == "1-59m v 1-11m" ~ "Child Azithro\n1-59m\nvs\nInfant Azithro\n1-11m",
        comparison == "Azithro 1-11m vs. Placebo" ~ "Infant Azithro\n1-11m\nvs\nPlacebo",
        comparison == "Azitrho 1-59m vs. Azithro 1-11m" ~ "Child Azithro\n1-59m\nvs\nInfant Azithro\n1-11m",
        TRUE ~ as.character(NA)
        
    ),
    outcome = case_when(
        is.na(outcome) & comparison == "1-59m v Placebo" ~ "Mortality among 1-59m olds",
        is.na(outcome) & comparison == "1-11m v Placebo" ~ "Mortality among 1-11m olds",
        is.na(outcome) & comparison == "1-59m v 1-11m" ~ "Mortality among 12-59m olds",
        TRUE ~ outcome
    )
           )

```


# Mortality rates by age and treatment


```{r plot mrates by treatment, fig.height = 6, fig.width=10}
#-------------------------------
# minor vars to help plot
#-------------------------------
d_mrates_tx3 <- d_mrates_tx2 %>%
    mutate(age_group_lab = case_when(
        age_group == "1to59" ~ "Ages 1-59m\nmortality",
        age_group == "1to11" ~ "Ages 1-11m\nmortality",
        age_group == "12to59" ~ "Ages 12-59m\nmortality",
    ), 
    age_group_lab = factor(age_group_lab, levels = c("Ages 1-59m\nmortality",  "Ages 1-11m\nmortality", "Ages 12-59m\nmortality")),
    txrev = factor(tx, levels=rev(levels(d_mrates_tx2$tx)))
    
    ) %>%
    arrange(age_group_lab,tx)



#-------------------------------
# plot rates, horizontal facet 
#-------------------------------
# pcols <- viridis_pal(end=0.7)(10)[c(1,4,7)]
# pcols <- brewer_pal(palette="PuBuGn")(9)[c(9,7,5)]
# pcols <- c(cbpal[4],cbpal[3],"gray20") # option 2
# pcols <- c(cbpal[4],cbpal[2],"gray20") # option 3
# pcols <- c(cbpal[7],cbpal[8],"gray20") # option 4
# pcols <- c(cbpal[6],cbpal[7],"gray20") # option 5
pcols <- c(cbpal[6],cbpal[2],"gray20") # option 6

plot_mrates_tx <- ggplot(data=d_mrates_tx3, aes(x = txlab, color = txlab, fill = txlab)) +
    facet_grid(.~age_group_lab) + 
    geom_errorbar(aes(ymin=mrate_min95, ymax=mrate_max95), width=0.1, alpha=1, lwd=0.4) + # color="gray20"
    # geom_point(aes(y = mrate), alpha=1, size=2, pch=21, color="gray20") +
    geom_point(aes(y = mrate), alpha=1, size=2, shape=3) +
    scale_y_continuous(breaks=seq(0,28,by=4)) + 
    # scale_fill_manual(values=pcols, guide = guide_legend(title="")) + 
    scale_color_manual(values=pcols) +
    labs(x="\nTreatment arm", y = "Deaths per 1,000 child-years") +
    coord_cartesian(ylim = c(0,26)) +
    theme_minimal() +
    theme(
        legend.position = "none",
        panel.grid.major.x = element_blank(),
        strip.text.x = element_text(angle=0, size=12),
        axis.text.x = element_text(angle=0),
        axis.title.x = element_text(size=12)
        # plot.tag = element_text(size=18,face="bold")
    )
plot_mrates_tx

ggsave(filename = here("output","Figure-2-avenir-mortality-rates.pdf"),
       plot_mrates_tx,
       device = "pdf",
       width = 180,
       height = 100,
       units = "mm")
```



# IRRs for each hypothesis

```{r plot irrs}
#-------------------------------
# Hypothesis 1: 1-59m treatment
#-------------------------------
plot_irr_h1 <- ggplot(data=d_irr %>% filter(hyp=="Hypothesis 1"), aes(x=irrlab, y=irr)) +
    geom_hline(yintercept = 1, color="white") +
    geom_hline(yintercept = 1, color="black", lty = "dashed") +
    geom_errorbar(aes(ymin=irr_min95, ymax=irr_max95), width=0.1, alpha=1,color="gray20") +
    geom_point(aes(y = irr), alpha=1, size=3, shape=3, color="gray20") +
    labs(x="",y="Percent change in mortality (%)", title = "Ages 1-59m\nmortality", subtitle = "", tag="A") +
    scale_y_continuous(breaks=seq(0.7,1.1,by=0.05), labels=seq(-30,10,by=5), trans="log") +
    coord_cartesian(ylim=c(0.7,1.11)) +
    theme_minimal() +
    theme(
        # axis.title.y = element_blank(),
        # axis.text.y = element_blank(),
        # axis.text.x = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(), 
        plot.title = element_text(hjust=0.5, size=10),
        plot.subtitle = element_text(size=8, hjust=0.5, vjust = 1),
        plot.tag = element_text(size=16,face = "bold")
        
    )

#-------------------------------
# Hypothesis 2: 1-11m treatment
#-------------------------------
plot_irr_h2 <- ggplot(data=d_irr %>% filter(hyp=="Hypothesis 2"), aes(x=irrlab, y=irr)) +
    geom_hline(yintercept = 1, color="white") +
    geom_hline(yintercept = 1, color="black", lty = "dashed") +
    geom_errorbar(aes(ymin=irr_min95, ymax=irr_max95), width=0.1, alpha=1,color="gray20") +
    geom_point(aes(y = irr), alpha=1, size=3, shape=3, color="gray20") +
    labs(x="",y="", title = "Ages 1-11m\nmortality", subtitle = "") +
    scale_y_continuous(breaks=seq(0.7,1.1,by=0.05), labels=seq(-30,10,by=5), trans="log") +
    coord_cartesian(ylim=c(0.7,1.11)) +
    theme_minimal() +
    theme(
        # axis.title.y = element_blank(),
        axis.text.y = element_blank(), 
        # axis.text.x = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(), 
        plot.title = element_text(hjust=0.5, size=10),
        plot.subtitle = element_text(size=8, hjust=0.5, vjust = 1)
        
    )

#-------------------------------
# Hypothesis 3: 12-59m treatment
#-------------------------------
plot_irr_h3 <- ggplot(data=d_irr %>% filter(hyp=="Hypothesis 3"), aes(x=irrlab, y=irr)) +
    geom_hline(yintercept = 1, color="white") +
    geom_hline(yintercept = 1, color="black", lty = "dashed") +
    geom_errorbar(aes(ymin=irr_min95, ymax=irr_max95), width=0.1, alpha=1,color="gray20") +
    geom_point(aes(y = irr), alpha=1, size=3, shape=3, color="gray20") +
    labs(x="",y="", title = "Ages 12-59m\nmortality", subtitle = "") +
    scale_y_continuous(breaks=seq(0.7,1.1,by=0.05), labels=seq(-30,10,by=5), trans="log") +
    coord_cartesian(ylim=c(0.7,1.11)) +
    theme_minimal() +
    theme(
        # axis.title.y = element_blank(),
        axis.text.y = element_blank(), 
        # axis.text.x = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(), 
        plot.title = element_text(hjust=0.5, size=10),
        plot.subtitle = element_text(size=8, hjust=0.5, vjust = 1)
        
    )

#-------------------------------
# Hypothesis 4: 1-11m indirect
#-------------------------------
plot_irr_h4 <- ggplot(data=d_irr %>% filter(hyp=="Hypothesis 4"), aes(x=irrlab, y=irr)) +
    geom_hline(yintercept = 1, color="white") +
    geom_hline(yintercept = 1, color="black", lty = "dashed") +
    geom_errorbar(aes(ymin=irr_min95, ymax=irr_max95), width=0.1, alpha=1,color="gray20") +
    geom_point(aes(y = irr), alpha=1, size=3, shape=3, color="gray20") +
    labs(x="",y="Percent change in mortality (%)", title = "Ages 12-59m\nmortality", subtitle = "(indirect effect)", tag = "B") +
    scale_y_continuous(breaks=seq(0.7,1.1,by=0.05), labels=seq(-30,10,by=5), trans="log") +
    coord_cartesian(ylim=c(0.7,1.11)) +
    theme_minimal() +
    theme(
        # axis.title.y = element_blank(),
        # axis.text.y = element_blank(),
        # axis.text.x = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(), 
        plot.title = element_text(hjust=0.5, size=10),
        plot.subtitle = element_text(size=8, hjust=0.5, vjust = 1),
        plot.tag = element_text(size=16,face = "bold")
        
    )

#-------------------------------
# Hypothesis 5: 1-59m indirect
#-------------------------------
plot_irr_h5 <- ggplot(data=d_irr %>% filter(hyp=="Hypothesis 5"), aes(x=irrlab, y=irr)) +
    geom_hline(yintercept = 1, color="white") +
    geom_hline(yintercept = 1, color="black", lty = "dashed") +
    geom_errorbar(aes(ymin=irr_min95, ymax=irr_max95), width=0.1, alpha=1,color="gray20") +
    geom_point(aes(y = irr), alpha=1, size=3, shape=3, color="gray20") +
    labs(x="",y="", title = "Ages 1-11m\nmortality", subtitle = "(indirect effect)") +
    scale_y_continuous(breaks=seq(0.7,1.1,by=0.05), labels=seq(-30,10,by=5), trans="log") +
    coord_cartesian(ylim=c(0.7,1.11)) +
    theme_minimal() +
    theme(
        # axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        # axis.text.x = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(), 
        plot.title = element_text(hjust=0.5, size=10),
        plot.subtitle = element_text(size=8, hjust=0.5, vjust = 1)
        
    )



#-------------------------------
# composite for irrs
#-------------------------------
# irr_primary <- plot_irr_h1  + plot_irr_h2  + plot_irr_h3 +
#     plot_layout(ncol=3, nrow=1) #+
#     # plot_annotation(title = "Primary outcomes") & theme(plot.title = element_text(hjust=5))
# 
# irr_secondary <- plot_irr_h4 + plot_irr_h5 +
#     plot_layout(ncol=2,nrow=1) #+
#     # plot_annotation(title = "Secondary outcomes")
# 
# irr_composite <- irr_primary + irr_secondary +
#     plot_layout(ncol=5, nrow=1)
layout <- "
ABC#DE
"
irr_composite <- plot_irr_h1  + plot_irr_h2  + plot_irr_h3 + plot_irr_h4 + plot_irr_h5 +
    plot_layout(design = layout) #+
    # plot_annotation(title = "                              Primary outcomes                                    Secondary outcomes")

irr_composite

ggsave(filename = here("output","Figure-3-avenir-mortality-reduction.pdf"),
       irr_composite,
       device = "pdf",
       width = 180,
       height = 110,
       units = "mm")

```




# Session Info
```{r session info}
sessionInfo()
```


